Rename PostForm kwargs
CMPUT404F21TEAM/social-distribution pull request #164
Opened 2021-11-11 02:35 UTC by olivier-vadiaval

Fix #156 
Renaming keyword args for PostForm

2021-11-11 06:13 UTC, JawadHossain requested changes

2021-11-11 06:13 UTC, JawadHossain commented on code/socialDistribution/views.py
> +        form = PostForm(request.POST, request.FILES, user_id=author.id)
we have to remove .id from the end of line 375. Otherwise, this will throw an error on post edit

2021-11-12 04:26 UTC, JawadHossain approved these changes

2021-11-13 19:42 UTC, debecerra approved these changes

2021-11-16 17:06 UTC, merged